package action

import (
	"os"

	"github.com/factly/bindu-server/util"
	"github.com/factly/x/loggerx"
	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/cors"

	"github.com/factly/bindu-server/action/category"
	"github.com/factly/bindu-server/action/chart"
	"github.com/factly/bindu-server/action/medium"
	"github.com/factly/bindu-server/action/organisation"
	"github.com/factly/bindu-server/action/tag"
	"github.com/factly/bindu-server/action/theme"
	_ "github.com/factly/bindu-server/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

//RegisterRoutes - to register routes
func RegisterRoutes() *chi.Mux {

	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(loggerx.Init())
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)
	r.Use(middleware.Heartbeat("/ping"))

	r.Use(cors.Handler(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token", "X-User", "X-Organisation"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: false,
		MaxAge:           300, // Maximum value not ignored by any of major browsers
	}))

	if envName, _ := os.LookupEnv("ENV"); envName == "development" {
		r.Get("/swagger/*", httpSwagger.WrapHandler)
	}

	r.With(util.CheckUser, util.CheckOrganisation).Group(func(r chi.Router) {
		r.Mount("/categories", category.Router())
		r.Mount("/charts", chart.Router())
		r.Mount("/media", medium.Router())
		r.Mount("/organisations", organisation.Router())
		r.Mount("/tags", tag.Router())
		r.Mount("/themes", theme.Router())
	})

	return r

}
