export const SET_SELECTED_ORGANISATION = 'SET_SELECTED_ORGANISATION';
export const GET_ORGANISATIONS_SUCCESS = 'GET_ORGANISATIONS_SUCCESS';
export const LOADING_ORGANISATIONS = 'LOADING_ORGANISATIONS';

export const API_GET_ORGANISATIONS = '/organisations';
