export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const ADD_TEMPLATES = 'ADD_TEMPLATES';
export const ADD_TEMPLATES_REQUEST = 'ADD_TEMPLATES_REQUEST';
export const SET_TEMPLATES_LOADING = 'SET_TEMPLATES_LOADING';
export const RESET_TEMPLATES = 'RESET_TEMPLATES';

export const TEMPLATES_API = '/templates';
